#!/usr/bin/env ruby
#
# How significant is dynamic dispatch vs. explicit conditionals?
#
# Test: Compare TrueClass/FalseClass polymorphism against if/else.

class TrueClass
  def if_true
    yield
  end
end

class FalseClass
  def if_true
    self
  end
end

require 'benchmark'
Benchmark.benchmark do |b|
  total = 0
  b.report('dispatch') do
    10000000.times do |i|
      (i % 3).zero?.if_true {total += 1}
    end
  end

  total = 0
  b.report('conditional') do
    10000000.times do |i|
      total += 1 if (i % 3).zero?
    end
  end
end
